In [11]:
mesh_data = {
    'polygon0': [1, 2, 3, 4],  # 例としてポリゴンの頂点のインデックスをリストで表現
    'polygon1': [5, 6, 7, 8],
    'polygon2': [9, 10, 11, 12]
}

# mesh_dataからpolygon0からpolygon2までのリストを取得します。
polygon_lists = [mesh_data[f'polygon{i}'] for i in range(3)]

from torch_geometric.loader import DataLoader

train_loader = DataLoader(polygon_lists, batch_size=2, shuffle=True)
test_loader = DataLoader(polygon_lists, batch_size=2)

for step, data in enumerate(train_loader):
    print(f"Step {step + 1}:")
    print("==========")
    # print(f"Number of graphs in the current batch: {data.num_graphs}")
    print(data)

print(polygon_lists)


Step 1:
[tensor([5, 1]), tensor([6, 2]), tensor([7, 3]), tensor([8, 4])]
Step 2:
[tensor([9]), tensor([10]), tensor([11]), tensor([12])]
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [19]:
import random

class Polygon:
    def __init__(self, polygon):
        self.nodeID = None


# Polygonインスタンスを作成し、リストに格納する
polygon_list = []
polygon_list.append(Polygon("polygon_0"))
polygon_list.append(Polygon("polygon_1"))
polygon_list.append(Polygon("polygon_2"))


# 名前からポリゴンにアクセスする関数
def access_polygon_by_name(name):
    for polygon in polygon_list:
        name.nodeID = random
        if polygon.nodeID == name:
            return polygon
    return None  # 該当する名前が見つからない場合はNoneを返す

# テスト
for i in range(4):
    name_to_access = f"polygon_{i}"
    found_polygon = access_polygon_by_name(name_to_access)
    if found_polygon:
        found_polygon.nodeID = random
        print(f"Found polygon with name '{name_to_access}': {found_polygon.nodeID}")
        
    else:
        print(f"Polygon with name '{name_to_access}' not found.")


Polygon with name 'polygon_0' not found.
Polygon with name 'polygon_1' not found.
Polygon with name 'polygon_2' not found.
Polygon with name 'polygon_3' not found.


In [22]:
class Polygon:
    def __init__(self, name, nodeID):
        self.name = name
        self.nodeID = nodeID

# 元のリストの各要素に対応するPolygonクラスのインスタンスを作成
polygon_list = ['polygon_705', 'polygon_3125', 'polygon_906', 'polygon_3182', 'polygon_2745', 'polygon_1836']
nodeID_list = [[0, 2], [2, 3, 4, 5, 7, 10], [0, 1], [3, 5, 8], [1, 4, 6, 7], [0, 2, 3]]

# Polygonインスタンスのリストを作成
polygon_instances = []
for name, nodeID in zip(polygon_list, nodeID_list):
    polygon_instances.append(Polygon(name, nodeID))

# 各ポリゴンの情報を表示
for polygon in polygon_instances:
    print(f"Polygon name: {polygon.name}")
    print(f"Node IDs: {polygon.nodeID}")
    print()


Polygon name: polygon_705
Node IDs: [0, 2]

Polygon name: polygon_3125
Node IDs: [2, 3, 4, 5, 7, 10]

Polygon name: polygon_906
Node IDs: [0, 1]

Polygon name: polygon_3182
Node IDs: [3, 5, 8]

Polygon name: polygon_2745
Node IDs: [1, 4, 6, 7]

Polygon name: polygon_1836
Node IDs: [0, 2, 3]



In [24]:
polygon_nodeID_dict = {
    'polygon_705': [0, 2],
    'polygon_3125': [2, 3, 4, 5, 7, 10],
    'polygon_906': [0, 1],
    'polygon_3182': [3, 5, 8],
    'polygon_2745': [1, 4, 6, 7],
    'polygon_1836': [0, 2, 3],}

data_loader = DataLoader(polygon_nodeID_dict, batch_size=3, shuffle=True)



In [29]:
for data in enumerate(data_loader):
    print("==========")
    print(data)


KeyError: 5

for文を使ってdictionaryに追加する方法

In [38]:
import torch

keyword_to_variables = {
    "keyword1": torch.tensor([1, 2]),
    "keyword2": torch.tensor([3, 4]),
}

# 新しいキーと値のペアを追加するリスト
new_keywords_and_variables = [
    ("keyword3", torch.tensor([5, 6])),
    ("keyword4", torch.tensor([7, 8])),
    # 追加するキーと値のペアを追加
]

# forループを使って新しいキーと値のペアをディクショナリに追加
for keyword, variables in new_keywords_and_variables:
    keyword_to_variables[keyword] = variables

print(keyword_to_variables)

for i in range(len(keyword_to_variables)):
    print(keyword_to_variables[f"keyword{i+1}"])


{'keyword1': tensor([1, 2]), 'keyword2': tensor([3, 4]), 'keyword3': tensor([5, 6]), 'keyword4': tensor([7, 8])}
tensor([1, 2])
tensor([3, 4])
tensor([5, 6])
tensor([7, 8])


In [6]:
import torch

# polygon.facesを定義
faces = torch.tensor([[1, 2, 0],
                      [2, 3, 0],
                      [0, 3, 5],
                      [0, 5, 6],
                      [0, 6, 4],
                      [0, 4, 1]])

# 各行の三角形からエッジを抽出してedge_indexを構築
edges = torch.cat([faces[:, [0, 1]],
                   faces[:, [1, 2]],
                   faces[:, [2, 0]]], dim=0)

# エッジのインデックスをソートして重複を削除
edge_index = torch.tensor(sorted(edges.numpy().tolist())).unique(dim=0)
edge_index = torch.transpose(edge_index, 0, 1)
print(edge_index)


tensor([[0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6],
        [1, 2, 3, 4, 5, 6, 0, 2, 0, 3, 0, 5, 0, 1, 0, 6, 0, 4]])


In [6]:
import torch

# 既存のテンソルを作成
existing_tensor = torch.tensor([[1, 2],
                                [3, 4]])

# 追加するテンソルの長さ（列数）を指定
num_columns_to_add = 3

# 追加するテンソルを作成
tensor_to_add = torch.ones(existing_tensor.size(0), num_columns_to_add, dtype=torch.int)

# 既存のテンソルと追加するテンソルを結合して新しいテンソルを作成
result = torch.cat((existing_tensor, tensor_to_add), dim=1)

print(result)



RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2 but got size 5 for tensor number 1 in the list.